# HYBRID NIDS CONFIGURATION

system:
  env: "development"
  log_level: "INFO"

network:
  interface: ""
  bpf_filter: "ip"
  promiscuous: true
  capture_mode: "offline"
  pcap_file: "pcap_samples/demo_attacks.pcap"

detection:
  rules_dir: "rules"
  enable_rule_engine: true
  enable_ai_worker: true
  queue_max_size: 10000

database:
  type: "sqlite"
  db_url: "sqlite:///nids_events.db"

api:
  host: "0.0.0.0"
  port: 8000
